language: "zh"

pipeline:
  - name: MitieNLP
    model: data/total_word_feature_extractor_zh.dat
  - name: JiebaTokenizer
    dictionary_path: data/dict.txt
  - name: MitieFeaturizer
  - name: RegexFeaturizer
    use_word_boundaries: False
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: bert-base-chinese
    cache_dir: data/bert-base-chinese
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: TEDPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: MappingPolicy
  - name: FormPolicy
  - name: RulePolicy